# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sg/mipt/homework/prog_tech/Kingdom_Fall

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sg/mipt/homework/prog_tech/Kingdom_Fall

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sg/mipt/homework/prog_tech/Kingdom_Fall/CMakeFiles /home/sg/mipt/homework/prog_tech/Kingdom_Fall/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sg/mipt/homework/prog_tech/Kingdom_Fall/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MyTest

# Build rule for target.
MyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MyTest
.PHONY : MyTest

# fast build rule for target.
MyTest/fast:
	$(MAKE) -f CMakeFiles/MyTest.dir/build.make CMakeFiles/MyTest.dir/build
.PHONY : MyTest/fast

src/CField.o: src/CField.cpp.o

.PHONY : src/CField.o

# target to build an object file
src/CField.cpp.o:
	$(MAKE) -f CMakeFiles/MyTest.dir/build.make CMakeFiles/MyTest.dir/src/CField.cpp.o
.PHONY : src/CField.cpp.o

src/CField.i: src/CField.cpp.i

.PHONY : src/CField.i

# target to preprocess a source file
src/CField.cpp.i:
	$(MAKE) -f CMakeFiles/MyTest.dir/build.make CMakeFiles/MyTest.dir/src/CField.cpp.i
.PHONY : src/CField.cpp.i

src/CField.s: src/CField.cpp.s

.PHONY : src/CField.s

# target to generate assembly for a file
src/CField.cpp.s:
	$(MAKE) -f CMakeFiles/MyTest.dir/build.make CMakeFiles/MyTest.dir/src/CField.cpp.s
.PHONY : src/CField.cpp.s

src/CObject.o: src/CObject.cpp.o

.PHONY : src/CObject.o

# target to build an object file
src/CObject.cpp.o:
	$(MAKE) -f CMakeFiles/MyTest.dir/build.make CMakeFiles/MyTest.dir/src/CObject.cpp.o
.PHONY : src/CObject.cpp.o

src/CObject.i: src/CObject.cpp.i

.PHONY : src/CObject.i

# target to preprocess a source file
src/CObject.cpp.i:
	$(MAKE) -f CMakeFiles/MyTest.dir/build.make CMakeFiles/MyTest.dir/src/CObject.cpp.i
.PHONY : src/CObject.cpp.i

src/CObject.s: src/CObject.cpp.s

.PHONY : src/CObject.s

# target to generate assembly for a file
src/CObject.cpp.s:
	$(MAKE) -f CMakeFiles/MyTest.dir/build.make CMakeFiles/MyTest.dir/src/CObject.cpp.s
.PHONY : src/CObject.cpp.s

src/CPosition.o: src/CPosition.cpp.o

.PHONY : src/CPosition.o

# target to build an object file
src/CPosition.cpp.o:
	$(MAKE) -f CMakeFiles/MyTest.dir/build.make CMakeFiles/MyTest.dir/src/CPosition.cpp.o
.PHONY : src/CPosition.cpp.o

src/CPosition.i: src/CPosition.cpp.i

.PHONY : src/CPosition.i

# target to preprocess a source file
src/CPosition.cpp.i:
	$(MAKE) -f CMakeFiles/MyTest.dir/build.make CMakeFiles/MyTest.dir/src/CPosition.cpp.i
.PHONY : src/CPosition.cpp.i

src/CPosition.s: src/CPosition.cpp.s

.PHONY : src/CPosition.s

# target to generate assembly for a file
src/CPosition.cpp.s:
	$(MAKE) -f CMakeFiles/MyTest.dir/build.make CMakeFiles/MyTest.dir/src/CPosition.cpp.s
.PHONY : src/CPosition.cpp.s

src/CUnit.o: src/CUnit.cpp.o

.PHONY : src/CUnit.o

# target to build an object file
src/CUnit.cpp.o:
	$(MAKE) -f CMakeFiles/MyTest.dir/build.make CMakeFiles/MyTest.dir/src/CUnit.cpp.o
.PHONY : src/CUnit.cpp.o

src/CUnit.i: src/CUnit.cpp.i

.PHONY : src/CUnit.i

# target to preprocess a source file
src/CUnit.cpp.i:
	$(MAKE) -f CMakeFiles/MyTest.dir/build.make CMakeFiles/MyTest.dir/src/CUnit.cpp.i
.PHONY : src/CUnit.cpp.i

src/CUnit.s: src/CUnit.cpp.s

.PHONY : src/CUnit.s

# target to generate assembly for a file
src/CUnit.cpp.s:
	$(MAKE) -f CMakeFiles/MyTest.dir/build.make CMakeFiles/MyTest.dir/src/CUnit.cpp.s
.PHONY : src/CUnit.cpp.s

src/CUnitFactory.o: src/CUnitFactory.cpp.o

.PHONY : src/CUnitFactory.o

# target to build an object file
src/CUnitFactory.cpp.o:
	$(MAKE) -f CMakeFiles/MyTest.dir/build.make CMakeFiles/MyTest.dir/src/CUnitFactory.cpp.o
.PHONY : src/CUnitFactory.cpp.o

src/CUnitFactory.i: src/CUnitFactory.cpp.i

.PHONY : src/CUnitFactory.i

# target to preprocess a source file
src/CUnitFactory.cpp.i:
	$(MAKE) -f CMakeFiles/MyTest.dir/build.make CMakeFiles/MyTest.dir/src/CUnitFactory.cpp.i
.PHONY : src/CUnitFactory.cpp.i

src/CUnitFactory.s: src/CUnitFactory.cpp.s

.PHONY : src/CUnitFactory.s

# target to generate assembly for a file
src/CUnitFactory.cpp.s:
	$(MAKE) -f CMakeFiles/MyTest.dir/build.make CMakeFiles/MyTest.dir/src/CUnitFactory.cpp.s
.PHONY : src/CUnitFactory.cpp.s

src/CUnitFactoryBuilder.o: src/CUnitFactoryBuilder.cpp.o

.PHONY : src/CUnitFactoryBuilder.o

# target to build an object file
src/CUnitFactoryBuilder.cpp.o:
	$(MAKE) -f CMakeFiles/MyTest.dir/build.make CMakeFiles/MyTest.dir/src/CUnitFactoryBuilder.cpp.o
.PHONY : src/CUnitFactoryBuilder.cpp.o

src/CUnitFactoryBuilder.i: src/CUnitFactoryBuilder.cpp.i

.PHONY : src/CUnitFactoryBuilder.i

# target to preprocess a source file
src/CUnitFactoryBuilder.cpp.i:
	$(MAKE) -f CMakeFiles/MyTest.dir/build.make CMakeFiles/MyTest.dir/src/CUnitFactoryBuilder.cpp.i
.PHONY : src/CUnitFactoryBuilder.cpp.i

src/CUnitFactoryBuilder.s: src/CUnitFactoryBuilder.cpp.s

.PHONY : src/CUnitFactoryBuilder.s

# target to generate assembly for a file
src/CUnitFactoryBuilder.cpp.s:
	$(MAKE) -f CMakeFiles/MyTest.dir/build.make CMakeFiles/MyTest.dir/src/CUnitFactoryBuilder.cpp.s
.PHONY : src/CUnitFactoryBuilder.cpp.s

test/test.o: test/test.cpp.o

.PHONY : test/test.o

# target to build an object file
test/test.cpp.o:
	$(MAKE) -f CMakeFiles/MyTest.dir/build.make CMakeFiles/MyTest.dir/test/test.cpp.o
.PHONY : test/test.cpp.o

test/test.i: test/test.cpp.i

.PHONY : test/test.i

# target to preprocess a source file
test/test.cpp.i:
	$(MAKE) -f CMakeFiles/MyTest.dir/build.make CMakeFiles/MyTest.dir/test/test.cpp.i
.PHONY : test/test.cpp.i

test/test.s: test/test.cpp.s

.PHONY : test/test.s

# target to generate assembly for a file
test/test.cpp.s:
	$(MAKE) -f CMakeFiles/MyTest.dir/build.make CMakeFiles/MyTest.dir/test/test.cpp.s
.PHONY : test/test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... MyTest"
	@echo "... src/CField.o"
	@echo "... src/CField.i"
	@echo "... src/CField.s"
	@echo "... src/CObject.o"
	@echo "... src/CObject.i"
	@echo "... src/CObject.s"
	@echo "... src/CPosition.o"
	@echo "... src/CPosition.i"
	@echo "... src/CPosition.s"
	@echo "... src/CUnit.o"
	@echo "... src/CUnit.i"
	@echo "... src/CUnit.s"
	@echo "... src/CUnitFactory.o"
	@echo "... src/CUnitFactory.i"
	@echo "... src/CUnitFactory.s"
	@echo "... src/CUnitFactoryBuilder.o"
	@echo "... src/CUnitFactoryBuilder.i"
	@echo "... src/CUnitFactoryBuilder.s"
	@echo "... test/test.o"
	@echo "... test/test.i"
	@echo "... test/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

